### ISSUE TITLE
Unable to display widgets on right side

### ISSUE THREAD

**Issue by KeithTanMing** [sg-smartmirror/sg-smartmirror#1]
Hi, 

Thanks for much for sharing your build. I'm based in SG, trying to create my own smart mirror proj and chanced upon your git, was perfect. 

My display is having an issue though. When i first cloned and ran the repo last week, it was working perfectly fine. Right now however, the clock, LTA and app widgets are missing. I didn't change anything substantial, except perhaps upgrading my python to 3.9.1.

Would you have any idea what's causing it?

Thanks!

**Comment by limjq45** [comment]
is there any errors showing up? I suspect it is some dependencies issue. When u change to python 3.9.1, do you have the required libraries in requirements.txt? 

If not I suspect that your python PATH needs to be changed.

**Comment by sg-smartmirror** [comment]
> Hi,
> 
> Thanks for much for sharing your build. I'm based in SG, trying to create my own smart mirror proj and chanced upon your git, was perfect.
> 
> My display is having an issue though. When i first cloned and ran the repo last week, it was working perfectly fine. Right now however, the clock, LTA and app widgets are missing. I didn't change anything substantial, except perhaps upgrading my python to 3.9.1.
> 
> Would you have any idea what's causing it?
> 
> Thanks!

is there any errors showing up? I suspect it is some dependencies issue. When u change to python 3.9.1, do you have the required libraries in requirements.txt?

If not I suspect that your python PATH needs to be changed.
